const DEV = false;

const BASETIMER = 5000;
const RSYNC_INTERVAL = DEV ? 2000 : 180000;
const HEARTBEAT_INTERVAL = 2000;
const HEARTBEAT_TIMER = 7000;
const RAFT_ELECTION_TIMER = 10000;
export { BASETIMER, RSYNC_INTERVAL, HEARTBEAT_INTERVAL, HEARTBEAT_TIMER, RAFT_ELECTION_TIMER };
